### ISSUE TITLE
Error using comunica stack to generate the website

### ISSUE THREAD

**Issue by dachafra** [RMLio/rml-implementation-report#15]
1) npm install (works perfectly)
2) npx eleventy outputs:

```
Require stack:
- /home/dchaves/rml-implementation-report/docs/my-sparql-engine/index.js
- /home/dchaves/rml-implementation-report/docs/graphqlexecutor.js
- /home/dchaves/rml-implementation-report/docs/_data/carml.js
- /home/dchaves/rml-implementation-report/docs/node_modules/@11ty/eleventy/src/TemplateData.js
- /home/dchaves/rml-implementation-report/docs/node_modules/@11ty/eleventy/src/Eleventy.js
- /home/dchaves/rml-implementation-report/docs/node_modules/@11ty/eleventy/cmd.js (Error):
    Error: Cannot find module '@comunica/actor-context-preprocess-rdf-source-identifier'

```

**Comment by pheyvaer** [comment]
Can you try the following

```
$ rm -rf node_modules
$ npm i
$ npx eleventy
```

This works for me (on `master`).

**Comment by dachafra** [comment]
same error :-(
I'm using 6.14.4 npm version

**Comment by pheyvaer** [comment]
And what version of node are you using? I'm at `v12.16.2`

**Comment by dachafra** [comment]
It's v13.13.0
I saw this warning in the npm install:

`npm WARN @comunica/actor-context-preprocess-rdf-source-identifier@1.13.0 requires a peer of @comunica/bus-rdf-source-identifier@^1.0.0 but none is installed. You must install peer dependencies yourself.`

**Comment by pheyvaer** [comment]
I removed `package-lock.json` and now I get the same error.

**Comment by pheyvaer** [comment]
I see that the code for Comunica it a bit outdated. It's better to update it. Does it actually work if you do a clean clone?

**Comment by dachafra** [comment]
I made a clone over a clean server (installing all from scratch) and it also outputs the error. It may a good idea to update it.
